name: OpsTron Notify
# This workflow notifies OpsTron every time you push code.
# OpsTron will enter "Watch Mode" and monitor your Docker containers
# for any errors that appear after the deployment.

on: [push]

jobs:
  notify-opstron:
    runs-on: ubuntu-latest
    name: Notify OpsTron of Deployment

    steps:
      - name: 📡 Trigger OpsTron Watch Mode
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.OPSTRON_BACKEND_URL }}
          method: 'POST'
          customHeaders: |
            {
              "Content-Type": "application/json",
              "x-hub-signature-256": "sha256=${{ secrets.OPSTRON_WEBHOOK_SECRET }}"
            }
          data: |
            {
              "event": "push",
              "repository": "${{ github.repository }}",
              "sha": "${{ github.sha }}",
              "ref": "${{ github.ref }}",
              "pusher": "${{ github.actor }}",
              "commit_message": "${{ github.event.head_commit.message }}"
            }
