"""
Error Models

Pydantic models for error payloads and RCA responses.
"""

from pydantic import BaseModel, Field
from typing import Optional, List, Dict, Any
from datetime import datetime


class ErrorPayload(BaseModel):
    """
    Structured error payload for automated ingestion.
    
    This model defines the contract between backend services and the RCA agent.
    Backend error middleware should format errors according to this schema.
    """
    
    # Required fields
    service: str = Field(
        ..., 
        description="Name of the service that generated the error",
        example="checkout-api"
    )
    error: str = Field(
        ..., 
        description="Error message or exception type",
        example="ValueError: Invalid input data"
    )
    
    # Error details
    stacktrace: str = Field(
        default="",
        description="Full stacktrace if available"
    )
    recent_logs: List[str] = Field(
        default_factory=list,
        description="Recent log lines for context (recommended: last 50-100 lines)"
    )
    
    # Context
    timestamp: str = Field(
        default_factory=lambda: datetime.utcnow().isoformat(),
        description="ISO format timestamp when error occurred"
    )
    env: str = Field(
        default="production",
        description="Environment (local, staging, production)"
    )
    
    # Request context (if applicable)
    request_id: Optional[str] = Field(
        default=None,
        description="Unique request identifier for tracing"
    )
    user_id: Optional[str] = Field(
        default=None,
        description="User ID if applicable (for user-triggered errors)"
    )
    endpoint: Optional[str] = Field(
        default=None,
        description="API endpoint that triggered the error",
        example="/api/v1/checkout"
    )
    method: Optional[str] = Field(
        default=None,
        description="HTTP method (GET, POST, etc.)"
    )
    
    # Additional metadata
    extra: Dict[str, Any] = Field(
        default_factory=dict,
        description="Additional custom metadata"
    )
    
    class Config:
        json_schema_extra = {
            "example": {
                "service": "checkout-api",
                "error": "ValueError: Invalid input data",
                "stacktrace": "Traceback (most recent call last):\n  File ...",
                "recent_logs": [
                    "2024-01-15 10:30:00 INFO Processing checkout",
                    "2024-01-15 10:30:01 ERROR Validation failed"
                ],
                "env": "production",
                "endpoint": "/api/v1/checkout",
                "method": "POST"
            }
        }


class RCAReport(BaseModel):
    """
    Root Cause Analysis report generated by the agent.
    """
    
    service: str = Field(description="Service that was analyzed")
    root_cause: str = Field(description="Identified root cause")
    confidence: str = Field(description="Confidence level: high, medium, low")
    
    contributing_factors: List[str] = Field(
        default_factory=list,
        description="Additional factors that may have contributed"
    )
    recommended_actions: List[str] = Field(
        default_factory=list,
        description="Recommended remediation steps"
    )
    related_commits: List[Dict[str, str]] = Field(
        default_factory=list,
        description="Recent commits that may be related"
    )
    runbook_matches: List[str] = Field(
        default_factory=list,
        description="Relevant runbooks found"
    )
    
    analyzed_at: str = Field(
        default_factory=lambda: datetime.utcnow().isoformat()
    )


class IngestResponse(BaseModel):
    """
    Response from error ingestion endpoint.
    """
    
    status: str = Field(
        description="Status: 'analyzed' or 'error'"
    )
    request_id: str = Field(
        description="Unique identifier for this analysis request"
    )
    rca_report: Dict[str, Any] = Field(
        description="The RCA analysis results"
    )
    processing_time_ms: float = Field(
        description="Time taken to process in milliseconds"
    )
